import json
from pathlib import Path
from typing import Any

from app.services.metrics_service import calculate_metrics

REPORT_DIR = Path("reports")


def _load_reports() -> list[dict[str, Any]]:
    """Load all workflow reports generated by the Command Center."""

    if not REPORT_DIR.exists():
        return []

    reports = []

    for file in REPORT_DIR.glob("workflow_report_*.json"):
        try:
            with open(file, "r", encoding="utf-8") as f:
                report = json.load(f)

            if isinstance(report, dict):
                reports.append(report)

        except (json.JSONDecodeError, OSError):
            continue

    reports.sort(
        key=lambda report: report.get("generated_at", ""),
        reverse=True,
    )

    return reports


def _build_recommendations(
    summary: dict[str, Any],
) -> list[dict[str, Any]]:
    """Generate actionable recommendations from real workflow metrics."""

    recommendations = []

    total = summary.get("total_tickets", 0)
    major_incidents = summary.get("major_incidents", 0)
    verification_failures = summary.get("verification_failures", 0)
    sla_rate = summary.get("sla_compliance_rate", 0)
    human_review_rate = summary.get("human_review_rate", 0)
    auto_resolution_rate = summary.get("auto_resolution_rate", 0)

    if major_incidents > 0:
        recommendations.append({
            "severity": "CRITICAL",
            "title": "Major incident detected",
            "message": f"{major_incidents} major incident(s) were detected.",
            "action": (
                "Prioritize incident command, assign an owner, "
                "and monitor recovery."
            ),
        })

    if verification_failures > 0:
        recommendations.append({
            "severity": "HIGH",
            "title": "Resolution verification failures",
            "message": (
                f"{verification_failures} ticket(s) failed "
                "post-action verification."
            ),
            "action": (
                "Review remediation actions and perform "
                "corrective remediation."
            ),
        })

    if sla_rate < 80 and total > 0:
        recommendations.append({
            "severity": "HIGH",
            "title": "SLA compliance risk",
            "message": f"SLA compliance is only {sla_rate:.1f}%.",
            "action": (
                "Prioritize SLA-sensitive tickets and "
                "escalate approaching breaches."
            ),
        })

    if human_review_rate >= 50 and total > 0:
        recommendations.append({
            "severity": "MEDIUM",
            "title": "High human-review dependency",
            "message": (
                f"{human_review_rate:.1f}% of tickets "
                "required human review."
            ),
            "action": (
                "Identify repeatable low-risk cases "
                "that can safely be automated."
            ),
        })

    if auto_resolution_rate == 0 and total > 0:
        recommendations.append({
            "severity": "MEDIUM",
            "title": "No automatic resolutions",
            "message": (
                "No ticket was successfully resolved automatically."
            ),
            "action": (
                "Review safe-remediation policies and "
                "identify low-risk actions."
            ),
        })

    if not recommendations:
        recommendations.append({
            "severity": "LOW",
            "title": "Operation is stable",
            "message": "No significant operational risks were detected.",
            "action": (
                "Continue monitoring SLA, resolution, "
                "and incident trends."
            ),
        })

    return recommendations


def _build_patterns(
    summary: dict[str, Any],
) -> list[dict[str, Any]]:
    """Convert metrics into operational patterns."""

    patterns = []

    total = summary.get("total_tickets", 0)

    if total == 0:
        return patterns

    human_review_rate = summary.get("human_review_rate", 0)
    verification_failure_rate = summary.get(
        "verification_failure_rate",
        0,
    )

    if human_review_rate >= 50:
        patterns.append({
            "type": "automation_gap",
            "severity": "MEDIUM",
            "finding": (
                "A large proportion of tickets "
                "require human intervention."
            ),
        })

    if verification_failure_rate >= 50:
        patterns.append({
            "type": "remediation_gap",
            "severity": "HIGH",
            "finding": (
                "Remediation attempts are not consistently "
                "producing verified recovery."
            ),
        })

    if summary.get("major_incidents", 0) > 0:
        patterns.append({
            "type": "major_incident",
            "severity": "CRITICAL",
            "finding": (
                "Critical service-impacting incidents "
                "were detected."
            ),
        })

    if summary.get("sla_compliance_rate", 100) < 80:
        patterns.append({
            "type": "sla_risk",
            "severity": "HIGH",
            "finding": (
                "SLA performance is below the recommended "
                "operational threshold."
            ),
        })

    return patterns


def generate_insights() -> dict[str, Any]:
    """Generate Command Center AI Insights."""

    summary = calculate_metrics()

    if summary.get("status") == "no_data":
        return {
            "status": "no_data",
            "message": "No workflow reports have been generated yet.",
            "summary": summary,
            "risk": {
                "level": "LOW",
            },
            "patterns": [],
            "recommendations": [],
            "major_incidents": [],
        }

    reports = _load_reports()

    latest = reports[0] if reports else {}

    generated_at = latest.get("generated_at")

    return {
        "status": "success",
        "generated_at": generated_at,

        "workflow": latest.get(
            "workflow",
            {},
        ),

        "summary": summary,

        "risk": {
            "level": summary.get(
                "risk_level",
                "LOW",
            ),
        },

        "patterns": _build_patterns(summary),

        "recommendations": _build_recommendations(summary),

        "major_incidents": summary.get(
            "major_incidents_report",
            [],
        ),
    }


def get_insight_history() -> dict[str, Any]:
    """Return historical workflow metrics."""

    reports = _load_reports()

    history = []

    for report in reports:
        summary = report.get("summary")

        if not summary:
            continue

        history.append({
            "generated_at": report.get("generated_at"),

            "workflow": report.get(
                "workflow",
                {},
            ),

            "summary": summary,
        })

    return {
        "status": "success",
        "count": len(history),
        "history": history,
    }